ubuntu@ip-172-31-31-98:~/ansible$ ansible -i hosts.txt all -m ping
The authenticity of host '18.220.248.216 (18.220.248.216)' can't be established.
ECDSA key fingerprint is SHA256:vumgAiwldMfZRd7dHed8x6PIsOWMcfIBCivYlq3G/4U.
Are you sure you want to continue connecting (yes/no)? ansible_user=ubuntu | UNREACHABLE! => {
    "changed": false,
    "msg": "Failed to connect to the host via ssh: ssh: Could not resolve hostname ansible_user=ubun                                                     tu: Name or service not known",
    "unreachable": true
}
yes
linux1 | UNREACHABLE! => {
    "changed": false,
    "msg": "Failed to connect to the host via ssh: Warning: Permanently added '18.220.248.216' (ECDS                                                     A) to the list of known hosts.\r\nPermission denied (publickey).",
    "unreachable": true
}
ubuntu@ip-172-31-31-98:~/ansible$ ansible -i hosts.txt all -m ping
ansible_user=ubuntu | UNREACHABLE! => {
    "changed": false,
    "msg": "Failed to connect to the host via ssh: ssh: Could not resolve hostname ansible_user=ubun                                                     tu: Name or service not known",
    "unreachable": true
}
linux1 | UNREACHABLE! => {
    "changed": false,
    "msg": "Failed to connect to the host via ssh: Permission denied (publickey).",
    "unreachable": true
}
ubuntu@ip-172-31-31-98:~/ansible$ ping 18.220.248.216
PING 18.220.248.216 (18.220.248.216) 56(84) bytes of data.

^C
--- 18.220.248.216 ping statistics ---
411 packets transmitted, 0 received, 100% packet loss, time 413280ms

ubuntu@ip-172-31-31-98:~/ansible$ ssh 18.229.248.216
^C
ubuntu@ip-172-31-31-98:~/ansible$ ssh ubuntu@18.229.248.216
^C
ubuntu@ip-172-31-31-98:~/ansible$ ssh -i ansible_server.pem ubuntu@18.229.248.216
Warning: Identity file ansible_server.pem not accessible: No such file or directory.
ssh: connect to host 18.229.248.216 port 22: Connection timed out
ubuntu@ip-172-31-31-98:~/ansible$ cd ~/.ssh
ubuntu@ip-172-31-31-98:~/.ssh$ ssh -i ansible_server.pem ubuntu@18.229.248.216
^C
ubuntu@ip-172-31-31-98:~/.ssh$ ssh -i ansible_server.pem ubuntu@172.31.29.146
The authenticity of host '172.31.29.146 (172.31.29.146)' can't be established.
ECDSA key fingerprint is SHA256:vumgAiwldMfZRd7dHed8x6PIsOWMcfIBCivYlq3G/4U.
Are you sure you want to continue connecting (yes/no)? yes
Warning: Permanently added '172.31.29.146' (ECDSA) to the list of known hosts.
Welcome to Ubuntu 16.04.7 LTS (GNU/Linux 4.4.0-1128-aws x86_64)

 * Documentation:  https://help.ubuntu.com
 * Management:     https://landscape.canonical.com
 * Support:        https://ubuntu.com/advantage

0 packages can be updated.
0 of these updates are security updates.



The programs included with the Ubuntu system are free software;
the exact distribution terms for each program are described in the
individual files in /usr/share/doc/*/copyright.

Ubuntu comes with ABSOLUTELY NO WARRANTY, to the extent permitted by
applicable law.

To run a command as administrator (user "root"), use "sudo <command>".
See "man sudo_root" for details.

ubuntu@ip-172-31-29-146:~$ exit
logout
Connection to 172.31.29.146 closed.
ubuntu@ip-172-31-31-98:~/.ssh$ ansible -i hosts.txt all -m ping
[WARNING]: Unable to parse /home/ubuntu/.ssh/hosts.txt as an inventory source
[WARNING]: No inventory was parsed, only implicit localhost is available
[WARNING]: provided hosts list is empty, only localhost is available. Note that the implicit
localhost does not match 'all'
ubuntu@ip-172-31-31-98:~/.ssh$ cd ~/ansible
ubuntu@ip-172-31-31-98:~/ansible$ ansible -i hosts.txt all -m ping
ansible_user=ubuntu | UNREACHABLE! => {
    "changed": false,
    "msg": "Failed to connect to the host via ssh: ssh: Could not resolve hostname ansible_user=ubun                                                     tu: Name or service not known",
    "unreachable": true
}
linux1 | UNREACHABLE! => {
    "changed": false,
    "msg": "Failed to connect to the host via ssh: Permission denied (publickey).",
    "unreachable": true
}
ubuntu@ip-172-31-31-98:~/ansible$ ping 172.31.29.146
PING 172.31.29.146 (172.31.29.146) 56(84) bytes of data.
^C
--- 172.31.29.146 ping statistics ---
16 packets transmitted, 0 received, 100% packet loss, time 15119ms

ubuntu@ip-172-31-31-98:~/ansible$ ssh -i ansible_server.pem ubuntu@172.31.29.146
Warning: Identity file ansible_server.pem not accessible: No such file or directory.
Permission denied (publickey).
ubuntu@ip-172-31-31-98:~/ansible$ cd ~/.ssh
ubuntu@ip-172-31-31-98:~/.ssh$ ssh -i ansible_server.pem ubuntu@172.31.29.146
Welcome to Ubuntu 16.04.7 LTS (GNU/Linux 4.4.0-1128-aws x86_64)

 * Documentation:  https://help.ubuntu.com
 * Management:     https://landscape.canonical.com
 * Support:        https://ubuntu.com/advantage

0 packages can be updated.
0 of these updates are security updates.

New release '18.04.5 LTS' available.
Run 'do-release-upgrade' to upgrade to it.


Last login: Wed May 26 19:55:46 2021 from 172.31.31.98
To run a command as administrator (user "root"), use "sudo <command>".
See "man sudo_root" for details.

ubuntu@ip-172-31-29-146:~$ exit
logout
Connection to 172.31.29.146 closed.
ubuntu@ip-172-31-31-98:~/.ssh$ ^C
ubuntu@ip-172-31-31-98:~/.ssh$ ansible -i hosts.txt all -m ping
[WARNING]: Unable to parse /home/ubuntu/.ssh/hosts.txt as an inventory source
[WARNING]: No inventory was parsed, only implicit localhost is available
[WARNING]: provided hosts list is empty, only localhost is available. Note that the implicit localhost does not
match 'all'
ubuntu@ip-172-31-31-98:~/.ssh$ cd ~/ansible
ubuntu@ip-172-31-31-98:~/ansible$ ansible -i hosts.txt all -m ping
ansible_user=ubuntu | UNREACHABLE! => {
    "changed": false,
    "msg": "Failed to connect to the host via ssh: ssh: Could not resolve hostname ansible_user=ubuntu: Name or s                                        ervice not known",
    "unreachable": true
}
linux1 | UNREACHABLE! => {
    "changed": false,
    "msg": "Failed to connect to the host via ssh: Permission denied (publickey).",
    "unreachable": true
}
ubuntu@ip-172-31-31-98:~/ansible$ touch ansible.cfg
ubuntu@ip-172-31-31-98:~/ansible$ ansible -i hosts.txt all -m ping
ansible_user=ubuntu | UNREACHABLE! => {
    "changed": false,
    "msg": "Failed to connect to the host via ssh: ssh: Could not resolve hostname ansible_user=ubuntu: Name or s                                        ervice not known",
    "unreachable": true
}
linux1 | SUCCESS => {
    "ansible_facts": {
        "discovered_interpreter_python": "/usr/bin/python3"
    },
    "changed": false,
    "ping": "pong"
}
ubuntu@ip-172-31-31-98:~/ansible$ ansible -i hosts.txt all -m ping
ansible_user=ubuntu | UNREACHABLE! => {
    "changed": false,
    "msg": "Failed to connect to the host via ssh: ssh: Could not resolve hostname ansible_user=ubuntu: Name or service not                               known",
    "unreachable": true
}
linux1 | SUCCESS => {
    "ansible_facts": {
        "discovered_interpreter_python": "/usr/bin/python3"
    },
    "changed": false,
    "ping": "pong"
}
ubuntu@ip-172-31-31-98:~/ansible$ ansible -i hosts.txt all -m ping
ansible_user=ubuntu | UNREACHABLE! => {
    "changed": false,
    "msg": "Failed to connect to the host via ssh: ssh: Could not resolve hostname ansible_user=ubuntu: Name or service not                               known",
    "unreachable": true
}
linux1 | SUCCESS => {
    "ansible_facts": {
        "discovered_interpreter_python": "/usr/bin/python3"
    },
    "changed": false,
    "ping": "pong"
}
ubuntu@ip-172-31-31-98:~/ansible$ ansible -i hosts.txt all -m ping
ansible_user=ubuntu | UNREACHABLE! => {
    "changed": false,
    "msg": "Failed to connect to the host via ssh: ssh: Could not resolve hostname ansible_user=ubuntu: Name or service not                               known",
    "unreachable": true
}
linux1 | SUCCESS => {
    "ansible_facts": {
        "discovered_interpreter_python": "/usr/bin/python3"
    },
    "changed": false,
    "ping": "pong"
}
ubuntu@ip-172-31-31-98:~/ansible$ ^C
ubuntu@ip-172-31-31-98:~/ansible$ Failed to connect to the host via ssh: ssh: Could not resolve hostname ansible_user=ubuntu: Nam                        e or service not       known"ansible -i hosts.txt all -m ping
> ansible -i hosts.txt all -m ping
> ^C
ubuntu@ip-172-31-31-98:~/ansible$ ansible -i hosts.txt all -m ping
ansible_user=ubuntu | UNREACHABLE! => {
    "changed": false,
    "msg": "Failed to connect to the host via ssh: ssh: Could not resolve hostname ansible_user=ubuntu: Name or service not known                        ",
    "unreachable": true
}
linux1 | SUCCESS => {
    "ansible_facts": {
        "discovered_interpreter_python": "/usr/bin/python3"
    },
    "changed": false,
    "ping": "pong"
}
ubuntu@ip-172-31-31-98:~/ansible$ ansible -i hosts.txt all -m ping
ansible_user=ubuntu | UNREACHABLE! => {
    "changed": false,
    "msg": "Failed to connect to the host via ssh: ssh: Could not resolve hostname ansible_user=ubuntu: Name or service not known                        ",
    "unreachable": true
}
linux1 | SUCCESS => {
    "ansible_facts": {
        "discovered_interpreter_python": "/usr/bin/python3"
    },
    "changed": false,
    "ping": "pong"
}
ubuntu@ip-172-31-31-98:~/ansible$ ansible all -m ping
ansible_user=ubuntu | UNREACHABLE! => {
    "changed": false,
    "msg": "Failed to connect to the host via ssh: ssh: Could not resolve hostname ansible_user=ubuntu: Name or service not known                        ",
    "unreachable": true
}
linux1 | SUCCESS => {
    "ansible_facts": {
        "discovered_interpreter_python": "/usr/bin/python3"
    },
    "changed": false,
    "ping": "pong"
}
ubuntu@ip-172-31-31-98:~/ansible$ ansible -i hosts.txt all -m ping
ansible_user=ubuntu | UNREACHABLE! => {
    "changed": false,
    "msg": "Failed to connect to the host via ssh: ssh: Could not resolve hostname ansible_user=ubuntu: Name or service not known                        ",
    "unreachable": true
}
linux1 | SUCCESS => {
    "ansible_facts": {
        "discovered_interpreter_python": "/usr/bin/python3"
    },
    "changed": false,
    "ping": "pong"
}
ubuntu@ip-172-31-31-98:~/ansible$ ls -la ~/
total 40
drwxr-xr-x 6 ubuntu ubuntu 4096 May 26 19:22 .
drwxr-xr-x 3 root   root   4096 May 26 18:56 ..
drwxrwxr-x 2 ubuntu ubuntu 4096 May 26 20:10 ansible
drwx------ 4 ubuntu ubuntu 4096 May 26 19:22 .ansible
-rw-r--r-- 1 ubuntu ubuntu  220 Aug 31  2015 .bash_logout
-rw-r--r-- 1 ubuntu ubuntu 3771 Aug 31  2015 .bashrc
drwx------ 2 ubuntu ubuntu 4096 May 26 18:57 .cache
-rw-r--r-- 1 ubuntu ubuntu  655 Jul 12  2019 .profile
drwx------ 2 ubuntu ubuntu 4096 May 26 19:22 .ssh
-rw-r--r-- 1 ubuntu ubuntu    0 May 26 18:58 .sudo_as_admin_successful
-rw------- 1 ubuntu ubuntu   61 May 26 18:57 .Xauthority
ubuntu@ip-172-31-31-98:~/ansible$ cd .ansible
-bash: cd: .ansible: No such file or directory
ubuntu@ip-172-31-31-98:~/ansible$ cd ~/
ubuntu@ip-172-31-31-98:~$ cd .ansible
ubuntu@ip-172-31-31-98:~/.ansible$ ls -la
total 16
drwx------ 4 ubuntu ubuntu 4096 May 26 19:22 .
drwxr-xr-x 6 ubuntu ubuntu 4096 May 26 19:22 ..
drwx------ 2 ubuntu ubuntu 4096 May 26 20:25 cp
drwx------ 2 ubuntu ubuntu 4096 May 26 20:24 tmp
ubuntu@ip-172-31-31-98:~/.ansible$ cd tmp
ubuntu@ip-172-31-31-98:~/.ansible/tmp$ ls -la
total 8
drwx------ 2 ubuntu ubuntu 4096 May 26 20:24 .
drwx------ 4 ubuntu ubuntu 4096 May 26 19:22 ..
ubuntu@ip-172-31-31-98:~/.ansible/tmp$ cd ~/ansible
ubuntu@ip-172-31-31-98:~/ansible$ ansible -i hosts.txt all -m ping -vvv
ansible 2.9.22
  config file = /home/ubuntu/ansible/ansible.cfg
  configured module search path = [u'/home/ubuntu/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python2.7/dist-packages/ansible
  executable location = /usr/bin/ansible
  python version = 2.7.12 (default, Mar  1 2021, 11:38:31) [GCC 5.4.0 20160609]
Using /home/ubuntu/ansible/ansible.cfg as config file
host_list declined parsing /home/ubuntu/ansible/hosts.txt as it did not pass its verify_file() method
script declined parsing /home/ubuntu/ansible/hosts.txt as it did not pass its verify_file() method
auto declined parsing /home/ubuntu/ansible/hosts.txt as it did not pass its verify_file() method
yaml declined parsing /home/ubuntu/ansible/hosts.txt as it did not pass its verify_file() method
Parsed /home/ubuntu/ansible/hosts.txt inventory source with ini plugin
Skipping callback 'actionable', as we already have a stdout callback.
Skipping callback 'counter_enabled', as we already have a stdout callback.
Skipping callback 'debug', as we already have a stdout callback.
Skipping callback 'dense', as we already have a stdout callback.
Skipping callback 'dense', as we already have a stdout callback.
Skipping callback 'full_skip', as we already have a stdout callback.
Skipping callback 'json', as we already have a stdout callback.
Skipping callback 'minimal', as we already have a stdout callback.
Skipping callback 'null', as we already have a stdout callback.
Skipping callback 'oneline', as we already have a stdout callback.
Skipping callback 'selective', as we already have a stdout callback.
Skipping callback 'skippy', as we already have a stdout callback.
Skipping callback 'stderr', as we already have a stdout callback.
Skipping callback 'unixy', as we already have a stdout callback.
Skipping callback 'yaml', as we already have a stdout callback.
META: ran handlers
<18.220.248.216> ESTABLISH SSH CONNECTION FOR USER: ubuntu
<18.220.248.216> SSH: EXEC ssh -C -o ControlMaster=auto -o ControlPersist=60s -o 'IdentityFile="/home/ubuntu/.ssh/ansible_server.                        pem"' -o KbdInteractiveAuthentication=no -o PreferredAuthentications=gssapi-with-mic,gssapi-keyex,hostbased,publickey -o Password                        Authentication=no -o 'User="ubuntu"' -o ConnectTimeout=10 -o ControlPath=/home/ubuntu/.ansible/cp/dcdf53f2c5 18.220.248.216 '/bin                        /sh -c '"'"'echo ~ubuntu && sleep 0'"'"''
<ansible_user=ubuntu> ESTABLISH SSH CONNECTION FOR USER: ubuntu
<ansible_user=ubuntu> SSH: EXEC ssh -C -o ControlMaster=auto -o ControlPersist=60s -o 'IdentityFile="/home/ubuntu/.ssh/ansible_se                        rver.pem"' -o KbdInteractiveAuthentication=no -o PreferredAuthentications=gssapi-with-mic,gssapi-keyex,hostbased,publickey -o Pas                        swordAuthentication=no -o 'User="ubuntu"' -o ConnectTimeout=10 -o ControlPath=/home/ubuntu/.ansible/cp/04cc4e89d9 ansible_user=ub                        untu '/bin/sh -c '"'"'echo ~ubuntu && sleep 0'"'"''
<ansible_user=ubuntu> (255, '', 'ssh: Could not resolve hostname ansible_user=ubuntu: Name or service not known\r\n')
ansible_user=ubuntu | UNREACHABLE! => {
    "changed": false,
    "msg": "Failed to connect to the host via ssh: ssh: Could not resolve hostname ansible_user=ubuntu: Name or service not known                        ",
    "unreachable": true
}
<18.220.248.216> (0, '/home/ubuntu\n', '')
<18.220.248.216> ESTABLISH SSH CONNECTION FOR USER: ubuntu
<18.220.248.216> SSH: EXEC ssh -C -o ControlMaster=auto -o ControlPersist=60s -o 'IdentityFile="/home/ubuntu/.ssh/ansible_server.                        pem"' -o KbdInteractiveAuthentication=no -o PreferredAuthentications=gssapi-with-mic,gssapi-keyex,hostbased,publickey -o Password                        Authentication=no -o 'User="ubuntu"' -o ConnectTimeout=10 -o ControlPath=/home/ubuntu/.ansible/cp/dcdf53f2c5 18.220.248.216 '/bin                        /sh -c '"'"'( umask 77 && mkdir -p "` echo /home/ubuntu/.ansible/tmp `"&& mkdir "` echo /home/ubuntu/.ansible/tmp/ansible-tmp-162                        2061335.12-4385-198424318663893 `" && echo ansible-tmp-1622061335.12-4385-198424318663893="` echo /home/ubuntu/.ansible/tmp/ansib                        le-tmp-1622061335.12-4385-198424318663893 `" ) && sleep 0'"'"''
<18.220.248.216> (0, 'ansible-tmp-1622061335.12-4385-198424318663893=/home/ubuntu/.ansible/tmp/ansible-tmp-1622061335.12-4385-198                        424318663893\n', '')
<linux1> Attempting python interpreter discovery
<18.220.248.216> ESTABLISH SSH CONNECTION FOR USER: ubuntu
<18.220.248.216> SSH: EXEC ssh -C -o ControlMaster=auto -o ControlPersist=60s -o 'IdentityFile="/home/ubuntu/.ssh/ansible_server.                        pem"' -o KbdInteractiveAuthentication=no -o PreferredAuthentications=gssapi-with-mic,gssapi-keyex,hostbased,publickey -o Password                        Authentication=no -o 'User="ubuntu"' -o ConnectTimeout=10 -o ControlPath=/home/ubuntu/.ansible/cp/dcdf53f2c5 18.220.248.216 '/bin                        /sh -c '"'"'echo PLATFORM; uname; echo FOUND; command -v '"'"'"'"'"'"'"'"'/usr/bin/python'"'"'"'"'"'"'"'"'; command -v '"'"'"'"'"                        '"'"'"'python3.7'"'"'"'"'"'"'"'"'; command -v '"'"'"'"'"'"'"'"'python3.6'"'"'"'"'"'"'"'"'; command -v '"'"'"'"'"'"'"'"'python3.5'                        "'"'"'"'"'"'"'"'; command -v '"'"'"'"'"'"'"'"'python2.7'"'"'"'"'"'"'"'"'; command -v '"'"'"'"'"'"'"'"'python2.6'"'"'"'"'"'"'"'"';                         command -v '"'"'"'"'"'"'"'"'/usr/libexec/platform-python'"'"'"'"'"'"'"'"'; command -v '"'"'"'"'"'"'"'"'/usr/bin/python3'"'"'"'"'                        "'"'"'"'; command -v '"'"'"'"'"'"'"'"'python'"'"'"'"'"'"'"'"'; echo ENDFOUND && sleep 0'"'"''
<18.220.248.216> (0, 'PLATFORM\nLinux\nFOUND\n/usr/bin/python3.5\n/usr/bin/python3\nENDFOUND\n', '')
<18.220.248.216> ESTABLISH SSH CONNECTION FOR USER: ubuntu
<18.220.248.216> SSH: EXEC ssh -C -o ControlMaster=auto -o ControlPersist=60s -o 'IdentityFile="/home/ubuntu/.ssh/ansible_server.                        pem"' -o KbdInteractiveAuthentication=no -o PreferredAuthentications=gssapi-with-mic,gssapi-keyex,hostbased,publickey -o Password                        Authentication=no -o 'User="ubuntu"' -o ConnectTimeout=10 -o ControlPath=/home/ubuntu/.ansible/cp/dcdf53f2c5 18.220.248.216 '/bin                        /sh -c '"'"'/usr/bin/python3.5 && sleep 0'"'"''
<18.220.248.216> (0, '{"platform_dist_result": ["Ubuntu", "16.04", "xenial"], "osrelease_content": "NAME=\\"Ubuntu\\"\\nVERSION=\                        \"16.04.7 LTS (Xenial Xerus)\\"\\nID=ubuntu\\nID_LIKE=debian\\nPRETTY_NAME=\\"Ubuntu 16.04.7 LTS\\"\\nVERSION_ID=\\"16.04\\"\\nHO                        ME_URL=\\"http://www.ubuntu.com/\\"\\nSUPPORT_URL=\\"http://help.ubuntu.com/\\"\\nBUG_REPORT_URL=\\"http://bugs.launchpad.net/ubu                        ntu/\\"\\nVERSION_CODENAME=xenial\\nUBUNTU_CODENAME=xenial\\n"}\n', '')
Using module file /usr/lib/python2.7/dist-packages/ansible/modules/system/ping.py
<18.220.248.216> PUT /home/ubuntu/.ansible/tmp/ansible-local-4380bTipJk/tmpNwbHgJ TO /home/ubuntu/.ansible/tmp/ansible-tmp-162206                        1335.12-4385-198424318663893/AnsiballZ_ping.py
<18.220.248.216> SSH: EXEC sftp -b - -C -o ControlMaster=auto -o ControlPersist=60s -o 'IdentityFile="/home/ubuntu/.ssh/ansible_s                        erver.pem"' -o KbdInteractiveAuthentication=no -o PreferredAuthentications=gssapi-with-mic,gssapi-keyex,hostbased,publickey -o Pa                        sswordAuthentication=no -o 'User="ubuntu"' -o ConnectTimeout=10 -o ControlPath=/home/ubuntu/.ansible/cp/dcdf53f2c5 '[18.220.248.2                        16]'
<18.220.248.216> (0, 'sftp> put /home/ubuntu/.ansible/tmp/ansible-local-4380bTipJk/tmpNwbHgJ /home/ubuntu/.ansible/tmp/ansible-tm                        p-1622061335.12-4385-198424318663893/AnsiballZ_ping.py\n', '')
<18.220.248.216> ESTABLISH SSH CONNECTION FOR USER: ubuntu
<18.220.248.216> SSH: EXEC ssh -C -o ControlMaster=auto -o ControlPersist=60s -o 'IdentityFile="/home/ubuntu/.ssh/ansible_server.                        pem"' -o KbdInteractiveAuthentication=no -o PreferredAuthentications=gssapi-with-mic,gssapi-keyex,hostbased,publickey -o Password                        Authentication=no -o 'User="ubuntu"' -o ConnectTimeout=10 -o ControlPath=/home/ubuntu/.ansible/cp/dcdf53f2c5 18.220.248.216 '/bin                        /sh -c '"'"'chmod u+x /home/ubuntu/.ansible/tmp/ansible-tmp-1622061335.12-4385-198424318663893/ /home/ubuntu/.ansible/tmp/ansible                        -tmp-1622061335.12-4385-198424318663893/AnsiballZ_ping.py && sleep 0'"'"''
<18.220.248.216> (0, '', '')
<18.220.248.216> ESTABLISH SSH CONNECTION FOR USER: ubuntu
<18.220.248.216> SSH: EXEC ssh -C -o ControlMaster=auto -o ControlPersist=60s -o 'IdentityFile="/home/ubuntu/.ssh/ansible_server.                        pem"' -o KbdInteractiveAuthentication=no -o PreferredAuthentications=gssapi-with-mic,gssapi-keyex,hostbased,publickey -o Password                        Authentication=no -o 'User="ubuntu"' -o ConnectTimeout=10 -o ControlPath=/home/ubuntu/.ansible/cp/dcdf53f2c5 -tt 18.220.248.216 '                        /bin/sh -c '"'"'/usr/bin/python3 /home/ubuntu/.ansible/tmp/ansible-tmp-1622061335.12-4385-198424318663893/AnsiballZ_ping.py && sl                        eep 0'"'"''
<18.220.248.216> (0, '\r\n{"ping": "pong", "invocation": {"module_args": {"data": "pong"}}}\r\n', 'Shared connection to 18.220.24                        8.216 closed.\r\n')
<18.220.248.216> ESTABLISH SSH CONNECTION FOR USER: ubuntu
<18.220.248.216> SSH: EXEC ssh -C -o ControlMaster=auto -o ControlPersist=60s -o 'IdentityFile="/home/ubuntu/.ssh/ansible_server.                        pem"' -o KbdInteractiveAuthentication=no -o PreferredAuthentications=gssapi-with-mic,gssapi-keyex,hostbased,publickey -o Password                        Authentication=no -o 'User="ubuntu"' -o ConnectTimeout=10 -o ControlPath=/home/ubuntu/.ansible/cp/dcdf53f2c5 18.220.248.216 '/bin                        /sh -c '"'"'rm -f -r /home/ubuntu/.ansible/tmp/ansible-tmp-1622061335.12-4385-198424318663893/ > /dev/null 2>&1 && sleep 0'"'"''
<18.220.248.216> (0, '', '')
linux1 | SUCCESS => {
    "ansible_facts": {
        "discovered_interpreter_python": "/usr/bin/python3"
    },
    "changed": false,
    "invocation": {
        "module_args": {
            "data": "pong"
        }
    },
    "ping": "pong"
}
META: ran handlers
META: ran handlers
ubuntu@ip-172-31-31-98:~/ansible$
